docker run -it \
-e POSTGRES_PASSWORD="root" \
-e POSTGRES_USER="root" \
-e POSTGRES_DB="ny_taxi" \
-e TZ="Asia/Jakarta" \
-e PGTZ="Asia/Jakarta" \
-p 5432:5432 \
-v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
postgres:13